### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by pacharanero** [Epidurio/epidur.io-ideas#1]
sounds trivial, but
* [x] Epidurio should have a logo at some point
* [ ] this logo should be on the avatar in github
* [x] && should be the favicon of the application itself

a very magnified and logoified cartoon of a Tuohy needle tip?

**Comment by timcknowles** [comment]
Some ideas:

https://docs.google.com/drawings/d/1FwvAYQ9B2Vk-aSdIE32z3_6pQPzi7rvfy__Cji7SMfQ/edit?usp=sharing
