### ISSUE TITLE
display on patient card the epidural status e.g. requested, completed, epidural wait time hhmm

### ISSUE THREAD

**Issue by timcknowles** [Epidurio/epidur.io-ideas#13]

**Comment by pacharanero** [comment]
request epidural => requested => completed is complete so far.

I'm not sure wait time is helpful on this UI screen, how does it help the MW or Anaes? It would certainly be useful analytics to draw out for auditing though, but that's another screen and another actor entirely.

closed by https://github.com/Epidurio/opal-epidur.io/pull/30
